Metodos_Numericos/Metodos_Numericos/Controllers/Capitulo2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Metodos_Numericos.Models;
using Metodos_Numericos.Algorithms;

namespace Metodos_Numericos.Controllers
{
    public class Capitulo2Controller : Controller
    { 
        //=================================================================== METODO BISECION =======================
        [HttpGet]
        public ActionResult MetodoBiseccion()
        {
            MetodoBiseccion_Model model = new MetodoBiseccion_Model();
            model.function = "x^3+4x^2-10";
            model.a=1;
            model.b=2;
            model.Tol=0.0000001;
            model.Iterator=50;
            MetodoDeBiseccion metbis = new MetodoDeBiseccion();
            model.ans = new Answer_Model();
            model.ans.status = 0;
            model.ans.Res = metbis.MetodoBiseccion(model.function, model.a, model.b, model.Tol, model.Iterator);
            return View(model);
        }
        [HttpPost]
        public ActionResult MetodoBiseccion(MetodoBiseccion_Model model, string submitbutton)
        {
            switch (submitbutton) 
            {
                case "Limpiar":
                    return View(model);
                default:
                    MetodoDeBiseccion metbis = new MetodoDeBiseccion();
                    model.ans = new Answer_Model();
                    model.ans.Res = metbis.MetodoBiseccion(model.function, model.a, model.b, model.Tol, model.Iterator);
                    if (model.ans.Res[0] == 'P')
                        model.ans.status = 1;
                    else
                        model.ans.status = 2;
                    return View(model);
            }

        }
        //=========================================================== METODO PUNTO FIJO ========================================
        [HttpGet]
        public ActionResult MetodoPuntoFijo() 
        {
            Metodopuntofijo_model model = new Metodopuntofijo_model();
            model.function1 = "x^3+4x^2-10";
            model.function2 = "(1/2)(10-x^3)^(1/2)";
            model.Aproximado=1.5;
            model.Tol=0.00001;
            model.Iteraciones=35;
            PuntoFijo metpunto = new PuntoFijo();
            model.ans = new Answer_Model();
            model.ans.Res = metpunto.puntofijo(model.function1, model.function2, model.Aproximado, model.Tol, model.Iteraciones);
            model.ans.status = 0;
            return View(model);
        }
        [HttpPost]
        public ActionResult MetodoPuntoFijo(Metodopuntofijo_model model, string submitbutton)
        {
            PuntoFijo metpunto = new PuntoFijo();
            model.ans = new Answer_Model();
            model.ans.Res = metpunto.puntofijo(model.function1, model.function2, model.Aproximado, model.Tol, model.Iteraciones);
            if (model.ans.Res[0] == 'L')
                model.ans.status = 1;
            else
                model.ans.status = 2;
            return View(model);
        }
        //=========================================================== METODO NEWTON ========================================
        [HttpGet]
        public ActionResult MetodoNewton() 
        {
            MetodoNewton_Model model = new MetodoNewton_Model();
            model.function1 = "cos(x)-x";
            model.function2 = "cos(x)-x";
            model.Aproximado = 0.74;
            model.Tol= 0.0001;
            model.Iteraciones=20;
            NewtonRaphson newton = new NewtonRaphson();
            model.ans = new Answer_Model();
            model.ans.Res = newton.newtonRaphson(model.function1, model.function2, model.Aproximado, model.Tol, model.Iteraciones);
            return View(model);
        }
        [HttpPost]
        public ActionResult MetodoNewton(MetodoNewton_Model model, string submitbutton) 
        {
            NewtonRaphson newton = new NewtonRaphson();
            model.ans = new Answer_Model();
            model.ans.Res = newton.newtonRaphson(model.function1, model.function2, model.Aproximado, model.Tol, model.Iteraciones);
            if (model.ans.Res[0] == 'L')
                model.ans.status = 1;
            else
                model.ans.status = 2;
            return View(model);
        }

        //==========================================================Metodo Secante=========================================
        [HttpGet]
        public ActionResult MetodoSecante()
        {
            metodoSecante_model model = new metodoSecante_model();
            model.function = "x^3 + 2x^2 + 10x - 20";
            model.XO = 0;
            model.X1 = 1;
            model.EPS = 0;
            model.EPSI = "0.001";
            model.MAXIT = 4;
            MetodoDeLaSecante metsec = new MetodoDeLaSecante();
            model.ans = new Answer_Model();
            metsec.function = "x^3 + 2x^2 + 10x - 20";
            metsec.XO = 0;
            metsec.Xl = 1;
            metsec.EPS = 0;
            metsec.EPSI = 0.001m;
            metsec.MAXIT = 4;
            model.ans.Res = metsec.solve();
            model.ans.status = 0;
            return View(model);
        }


        [HttpPost]
        public ActionResult MetodoSecante(metodoSecante_model model, string submitbutton)
        {
            MetodoDeLaSecante metsec = new MetodoDeLaSecante();
            model.ans = new Answer_Model();
            metsec.function = model.function;
            metsec.XO = model.XO;
            metsec.Xl = model.X1;
            metsec.EPS = model.EPS;
            metsec.EPSI = Convert.ToDecimal(model.EPSI);
            metsec.MAXIT = model.MAXIT;
            model.ans.Res = metsec.solve();
            if (model.ans.Res[0] == 'L')
                model.ans.status = 1;
            else
                model.ans.status = 2;
            return View(model);
        }

        //===========================================Falsa Posicion=====================================================
        [HttpGet]
        public ActionResult MetodoFalsaPosicion()
        {
            falsaPosicion_model model = new falsaPosicion_model();
            model.ecuacion = "cos(x)-x";
            model.aproximacionP0 = 0.5;
            model.aproximacionP1 = 0.785398;
            model.toleracia = 0.01;
            model.iteraciones = 7;
            PosicionFalsa Fpos = new PosicionFalsa();
            model.ans = new Answer_Model();
            model.ans.Res = Fpos.Calculate(model.ecuacion, model.aproximacionP0, model.aproximacionP1, model.toleracia, model.iteraciones);
            model.ans.status = 0;
            return View(model);
        }

        [HttpPost]
        public ActionResult MetodoFalsaPosicion(falsaPosicion_model model, string submitbutton)
        {

            PosicionFalsa Fpos = new PosicionFalsa();
            model.ans = new Answer_Model();
            model.ans.Res = Fpos.Calculate(model.ecuacion, model.aproximacionP0, model.aproximacionP1, model.toleracia, model.iteraciones);
            if (model.ans.Res[0] == 'L')
                model.ans.status = 1;
            else
                model.ans.status = 2;
            return View(model);
        }

        //=============================================== Muller===============================================
        [HttpGet]
        public ActionResult Muller()
        {
            Muller_model model = new Muller_model();
            model.function = "16x^4-40x^3+5x^2+20x+6";
            model.X0 = 0.5m;
            model.X1 = 1;
            model.X2 = 1.5m;
            model.tolerancia = "0.001";
            model.iteraciones = 25;
            Muller mullerMet = new Muller();
            model.ans = new Answer_Model();
            mullerMet.Function = "x^3 + 2x^2 + 10x - 20";
            mullerMet.X0 = 0.5m;
            mullerMet.X1 = 1;
            mullerMet.X2 = 1.5m;
            mullerMet.Tol = 0.001m;
            mullerMet.N = (decimal)25;
            model.ans.Res = mullerMet.Solve();
            model.ans.status = 0;
            return View(model);
        }

        [HttpPost]
        public ActionResult Muller(Muller_model model, string submitbutton)
        {
            Muller mullerMet = new Muller();
            model.ans = new Answer_Model();
            mullerMet.Function = model.function;
            mullerMet.X0 = model.X0;
            mullerMet.X1 = model.X1;
            mullerMet.X2 = model.X2;
            mullerMet.Tol = Convert.ToDecimal(model.tolerancia);
            mullerMet.N = (decimal)model.iteraciones;
            model.ans.Res = mullerMet.Solve();
            model.ans.status = 0;

            if (model.ans.Res[0] == 'S')
                model.ans.status = 1;
            else
                model.ans.status = 2;
            return View(model);
        }





        [ChildActionOnly]
        public ActionResult _Respuesta(Answer_Model model)
        {
            return PartialView(model);
        }
    }
}

Metodos_Numericos/Metodos_Numericos/Views/Shared/Helper.cshtml
@helper HelperName(string name) {
    // your helper can contain code and/or markup, e.g.
    // var msg = "Hello " + name;
    // <p>@msg</p>
    // For more information, visit http://go.microsoft.com/fwlink/?LinkID=204658
}

Metodos_Numericos/Metodos_Numericos/Views/Shared/_Layout.cshtml
@model Metodos_Numericos.Models.BaseModel

<!DOCTYPE html>
<html>
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>@Page.Title</title>
        @RenderSection("head", required: false)
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Content/Layout.css" rel="stylesheet" />
        <link href="~/fonts/font-awesome/css/font-awesome.css" rel="stylesheet" />

    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar nav-tabs navbar-fixed-top" role="navigation">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand">@ViewBag.Title</a>
                </div>

                @using ( Html.BeginForm( "Search", "Home", FormMethod.Post, new
                {
                    @class = "navbar-form navbar-right hidden-xs",
                    role = "search"
                } ) )
                {
                    // ESTO ES EL LOGO
                    <div>
                        <img src=""/>
                    </div>
                  
                }

                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav side-nav">

                        <li>
                            <a href="javascript:;" data-toggle="collapse" data-target="#drop1"> --˃ Lista de ecuaciones 2 <i class="fa fa-fw fa-caret-down"></i></a>
                            <ul id="drop1" class="collapse">
                                <li>
                                    <a href="@Url.Action("MetodoBiseccion","Capitulo2")">1 Método Bisección</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("MetodoPuntoFijo", "Capitulo2")">2 Método de Punto Fijo</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("MetodoNewton", "Capitulo2")">3 Método de Newton</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("metodoSecante","Capitulo2")">4 Método de La Secante</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("metodoFalsaPosicion","Capitulo2")">5 Método de Falsa Posición</a>
                                </li>
                                <!--<li>
                                    <a href="@Url.Action("Muller","Capitulo2")">2.6 Método de Müller</a>
                                </li>-->
                            </ul>
                        </li>

                        <li>
                            <a href="javascript:;" data-toggle="collapse" data-target="#drop2"> --˃ Lista de ecuaciones 3 <i class="fa fa-fw fa-caret-down"></i></a>
                            <ul id="drop2" class="collapse">
                                <li>
                                    <a href="@Url.Action("Lagrange", "Capitulo3")">1 Interpolación de Lagrange</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("InterNewton", "Capitulo3")">2 Interpolación Polinomimal de Newton</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("TrazadorSujeto", "Capitulo3")">3 Interpolación Mediante Trazadores Cúbicos Sujetos</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("TrazadorNatural", "Capitulo3")">4 Interpolación Mediante Trazadores Cúbicos Naturales</a>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <a href="javascript:;" data-toggle="collapse" data-target="#drop3"> --˃ Lista de ecuaciones 4 <i class="fa fa-fw fa-caret-down"></i></a>
                            <ul id="drop3" class="collapse">
                                <li>
                                    <a href="@Url.Action( "DiferenciacionNumerica", "Capitulo4" )"> 1 Diferenciación Númerica. </a>
                                </li>
                                <li>
                                    <a href="@Url.Action( "ReglaTrapecio", "Capitulo4" )"> 2 Integración Númerica: Regla de Trapecio. </a>
                                </li>
                                <li>
                                    <a href="@Url.Action( "Simpson", "Capitulo4" )"> 3 Integración Númerica: Simpson. </a>
                                </li>

                                <li>
                                    <a href="@Url.Action( "CuadraturaGauss", "Capitulo4" )"> 4 Integracion Numerica: Cuadraturas de Gauss. </a>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <a href="javascript:;" data-toggle="collapse" data-target="#drop4"> --˃ Lista de ecuaciones 5 <i class="fa fa-fw fa-caret-down"></i></a>
                            <ul id="drop4" class="collapse">
                                <li>
                                    <a href="@Url.Action( "MetodoDeEuler", "Capitulo5" )"> 1 Solucion de Edo: Metodo de Euler. </a>
                                </li>
                                <li>
                                    <a href="@Url.Action( "SolucionEdoRK", "Capitulo5" )"> 2 Solución de Edo: Runge-Kutta </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("SistemaEdoRK", "Capitulo5")"> 3 Sistema de Edo: Runge-Kutta </a>
                                </li>
                            </ul>
                        </li>

                      <li>
                            <a href="javascript:;" data-toggle="collapse" data-target="#drop5"> --˃ Lista de ecuaciones 6 <i class="fa fa-fw fa-caret-down"></i></a>
                            <ul id="drop5" class="collapse">
                                <li>
                                    <a href="@Url.Action("EliminacionDeGauss", "Capitulo6")">1 Sistema de ecuaciones por eliminación de Gauss</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("EliminacionDeGaussJordan", "Capitulo6")">2 Sistema de ecuaciones por eliminación de Gauss Jordan</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("SistemaEcuacionesInversa", "Capitulo6")">3 Sistema de ecuaciones mediante la inversa</a>
                                </li>
                            </ul>
                        </li>

                       <li>
                            <a href="javascript:;" data-toggle="collapse" data-target="#drop6"> --> Lista de ecuaciones 7 <i class="fa fa-fw fa-caret-down"></i></a>
                            <ul id="drop6" class="collapse">
                                <li>
                                    <a href="@Url.Action( "RegresionLineal", "Capitulo8" )"> 1 Regresion lineal. </a>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <a href="javascript:;" data-toggle="collapse" data-target="#drop7"> --> Continuacion Metodos lineal de diferencias finitas <i class="fa fa-fw fa-caret-down"></i></a>
                            <ul id="drop7" class="collapse">
                                <li>
                                    <a href="@Url.Action( "DiferenciasFinitas", "Capitulo11" )"> 2 Método Lineal de diferencias finitas. </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>

            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </div>

        </div>
        <script src="~/Scripts/jquery-2.1.4.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
    </body>
</html>

Metodos_Numericos/Metodos_Numericos/Views/Shared/_Respuesta.cshtml
@model Metodos_Numericos.Models.Answer_Model

<div>
    <hr />
    @if (Model.status.Equals(0))
    {
        <div class="col-md-offset-4 col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>Salida</h3>
                </div>
                <div class="panel-body">
                    @Html.DisplayTextFor(model => model.Res)
                </div>
                <div class="panel-footer">
                </div>
            </div>
        </div>
    }
    else if (Model.status.Equals(1))
    {
        <div class="col-md-offset-4 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <h3>Salida</h3>
                </div>
                <div class="panel-body">
                    @Html.DisplayTextFor(model => model.Res)
                </div>
                <div class="panel-footer">
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="col-md-offset-4 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <h3>Error</h3>
                </div>
                <div class="panel-body">
                    @Html.DisplayTextFor(model => model.Res)
                </div>
                <div class="panel-footer">
                </div>
            </div>
        </div>
    }
</div>